[package]
name = "temperature"
version = "0.1.0"
authors = ["Dvlv <Dvlv@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systemstat="0.1.5"
